// Generated by gencpp from file detect_msgs/Yolo_Objects.msg
// DO NOT EDIT!


#ifndef DETECT_MSGS_MESSAGE_YOLO_OBJECTS_H
#define DETECT_MSGS_MESSAGE_YOLO_OBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <detect_msgs/Objects.h>

namespace detect_msgs
{
template <class ContainerAllocator>
struct Yolo_Objects_
{
  typedef Yolo_Objects_<ContainerAllocator> Type;

  Yolo_Objects_()
    : header()
    , yolo_objects()  {
    }
  Yolo_Objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , yolo_objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::detect_msgs::Objects_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::detect_msgs::Objects_<ContainerAllocator> >> _yolo_objects_type;
  _yolo_objects_type yolo_objects;





  typedef boost::shared_ptr< ::detect_msgs::Yolo_Objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_msgs::Yolo_Objects_<ContainerAllocator> const> ConstPtr;

}; // struct Yolo_Objects_

typedef ::detect_msgs::Yolo_Objects_<std::allocator<void> > Yolo_Objects;

typedef boost::shared_ptr< ::detect_msgs::Yolo_Objects > Yolo_ObjectsPtr;
typedef boost::shared_ptr< ::detect_msgs::Yolo_Objects const> Yolo_ObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_msgs::Yolo_Objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detect_msgs::Yolo_Objects_<ContainerAllocator1> & lhs, const ::detect_msgs::Yolo_Objects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.yolo_objects == rhs.yolo_objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detect_msgs::Yolo_Objects_<ContainerAllocator1> & lhs, const ::detect_msgs::Yolo_Objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detect_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_msgs::Yolo_Objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_msgs::Yolo_Objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_msgs::Yolo_Objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f94689ed67d6f56bbe6b59436a3a900";
  }

  static const char* value(const ::detect_msgs::Yolo_Objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f94689ed67d6f56ULL;
  static const uint64_t static_value2 = 0xbbe6b59436a3a900ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_msgs/Yolo_Objects";
  }

  static const char* value(const ::detect_msgs::Yolo_Objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Objects[] yolo_objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: detect_msgs/Objects\n"
"int32 Class\n"
"int32 id\n"
"int32 x1\n"
"int32 x2\n"
"int32 y1\n"
"int32 y2\n"
;
  }

  static const char* value(const ::detect_msgs::Yolo_Objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.yolo_objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Yolo_Objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_msgs::Yolo_Objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_msgs::Yolo_Objects_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yolo_objects: ";
    if (v.yolo_objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.yolo_objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::detect_msgs::Objects_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.yolo_objects[i]);
    }
    if (v.yolo_objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_MSGS_MESSAGE_YOLO_OBJECTS_H
