// Generated by gencpp from file detect_msgs/detected_array.msg
// DO NOT EDIT!


#ifndef DETECT_MSGS_MESSAGE_DETECTED_ARRAY_H
#define DETECT_MSGS_MESSAGE_DETECTED_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <detect_msgs/detected_object.h>

namespace detect_msgs
{
template <class ContainerAllocator>
struct detected_array_
{
  typedef detected_array_<ContainerAllocator> Type;

  detected_array_()
    : header()
    , objects()  {
    }
  detected_array_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::detect_msgs::detected_object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::detect_msgs::detected_object_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::detect_msgs::detected_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_msgs::detected_array_<ContainerAllocator> const> ConstPtr;

}; // struct detected_array_

typedef ::detect_msgs::detected_array_<std::allocator<void> > detected_array;

typedef boost::shared_ptr< ::detect_msgs::detected_array > detected_arrayPtr;
typedef boost::shared_ptr< ::detect_msgs::detected_array const> detected_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_msgs::detected_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_msgs::detected_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detect_msgs::detected_array_<ContainerAllocator1> & lhs, const ::detect_msgs::detected_array_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detect_msgs::detected_array_<ContainerAllocator1> & lhs, const ::detect_msgs::detected_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detect_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detect_msgs::detected_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_msgs::detected_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_msgs::detected_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_msgs::detected_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_msgs::detected_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_msgs::detected_array_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_msgs::detected_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e13babe394ae7d5a46bd763bac5f5b3";
  }

  static const char* value(const ::detect_msgs::detected_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e13babe394ae7d5ULL;
  static const uint64_t static_value2 = 0xa46bd763bac5f5b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_msgs::detected_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_msgs/detected_array";
  }

  static const char* value(const ::detect_msgs::detected_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_msgs::detected_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"detected_object[] objects\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: detect_msgs/detected_object\n"
"int64 id\n"
"geometry_msgs/Pose world_point\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::detect_msgs::detected_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_msgs::detected_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detected_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_msgs::detected_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_msgs::detected_array_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::detect_msgs::detected_object_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_MSGS_MESSAGE_DETECTED_ARRAY_H
