// Generated by gencpp from file detect_msgs/Objects.msg
// DO NOT EDIT!


#ifndef DETECT_MSGS_MESSAGE_OBJECTS_H
#define DETECT_MSGS_MESSAGE_OBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_msgs
{
template <class ContainerAllocator>
struct Objects_
{
  typedef Objects_<ContainerAllocator> Type;

  Objects_()
    : Class(0)
    , id(0)
    , x1(0)
    , x2(0)
    , y1(0)
    , y2(0)  {
    }
  Objects_(const ContainerAllocator& _alloc)
    : Class(0)
    , id(0)
    , x1(0)
    , x2(0)
    , y1(0)
    , y2(0)  {
  (void)_alloc;
    }



   typedef int32_t _Class_type;
  _Class_type Class;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _x1_type;
  _x1_type x1;

   typedef int32_t _x2_type;
  _x2_type x2;

   typedef int32_t _y1_type;
  _y1_type y1;

   typedef int32_t _y2_type;
  _y2_type y2;





  typedef boost::shared_ptr< ::detect_msgs::Objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_msgs::Objects_<ContainerAllocator> const> ConstPtr;

}; // struct Objects_

typedef ::detect_msgs::Objects_<std::allocator<void> > Objects;

typedef boost::shared_ptr< ::detect_msgs::Objects > ObjectsPtr;
typedef boost::shared_ptr< ::detect_msgs::Objects const> ObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_msgs::Objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_msgs::Objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detect_msgs::Objects_<ContainerAllocator1> & lhs, const ::detect_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return lhs.Class == rhs.Class &&
    lhs.id == rhs.id &&
    lhs.x1 == rhs.x1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y1 == rhs.y1 &&
    lhs.y2 == rhs.y2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detect_msgs::Objects_<ContainerAllocator1> & lhs, const ::detect_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detect_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detect_msgs::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_msgs::Objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_msgs::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_msgs::Objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_msgs::Objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_msgs::Objects_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c3939f535e7f9cd3b8fb5460ead7a6b";
  }

  static const char* value(const ::detect_msgs::Objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c3939f535e7f9cdULL;
  static const uint64_t static_value2 = 0x3b8fb5460ead7a6bULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_msgs/Objects";
  }

  static const char* value(const ::detect_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Class\n"
"int32 id\n"
"int32 x1\n"
"int32 x2\n"
"int32 y1\n"
"int32 y2\n"
;
  }

  static const char* value(const ::detect_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_msgs::Objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.id);
      stream.next(m.x1);
      stream.next(m.x2);
      stream.next(m.y1);
      stream.next(m.y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_msgs::Objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_msgs::Objects_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Class: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_MSGS_MESSAGE_OBJECTS_H
